version: "3.8"
services:
  frontend:
    build: ./FrontendService/fullstack-React-frontend
    command: npm run start
    container_name: frontend
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - mysqldb


  api_server:
    build: ./BlogService/fullstack-blogapi-backend
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mysqldb


  auth_server:
    build: ./AuthService/fullstack-authserver-backend
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysqldb


  mysqldb:
    platform: linux/x86_64
    image: "mysql:5.7"
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: springversion
      MYSQL_USER: root
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: mypassword